
homere_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 25
  extra_joints:
    - name: 'left_caster_ax1_to_ax2_joint'
    - name: 'right_caster_ax1_to_ax2_joint'
    - name: 'left_caster_fork_to_wheel_joint'
    - name: 'right_caster_fork_to_wheel_joint'

    
homere_controller:
    type: homere_control/HomereController
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    lw_kp: 1.0
    rw_kp: 1.0
    lw_ki: 1.
    rw_ki: 1.
    lw_kd: 0.
    rw_kd: 0.


homere_imu_controller:
  type: imu_sensor_controller/ImuSensorController
  publish_rate: 25
