homere:
  homere_joint_publisher:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  homere_imu_controller:
    type: imu_sensor_controller/ImuSensorController
    publish_rate: 25

  homere_controller:
    type: homere_control/HomereController
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    lw_kp: 4.0
    rw_kp: 4.0
    lw_ki: 1.
    rw_ki: 1.
    lw_kd: 2.
    rw_kd: 2.
    odom_ws: 0.75
    odom_lr: 0.2
    odom_rr: 0.2

